# Generated by Django 4.2.4 on 2023-09-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gomokunarabe', '0002_game_delete_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='moves',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('mark', models.CharField(max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_moves', to='gomokunarabe.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gomokunarabe.player')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='gomokunarabe.game')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='gomokunarabe.board')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='gomokunarabe.mark')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='gomokunarabe.board'),
        ),
    ]
